(library
 (name test_support)
 (modules database database_migration)
 (wrapped false)
 (libraries
  alcotest-lwt
  caqti-driver-mariadb
  caqti-driver-postgresql
  lwt_ppx
  sihl)
 (preprocess
  (pps lwt_ppx)))

(executables
 (names
  core_app
  core_configuration
  core_container
  core_utils
  database_mariadb
  database_migration_mariadb
  database_migration_postgresql
  database_postgresql
  web
  web_csrf
  web_flash
  web_http
  web_id
  web_session
  web_trailing_slash)
 (modules
  core_app
  core_configuration
  core_container
  core_utils
  database_mariadb
  database_migration_mariadb
  database_migration_postgresql
  database_postgresql
  web
  web_csrf
  web_flash
  web_http
  web_id
  web_session
  web_trailing_slash)
 (libraries
  alcotest-lwt
  caqti-driver-mariadb
  caqti-driver-postgresql
  cohttp-lwt-unix
  lwt_ppx
  rock
  sihl
  test_support)
 (preprocess
  (pps
   lwt_ppx
   ppx_deriving_yojson
   ppx_deriving.eq
   ppx_deriving.make
   ppx_deriving.show
   ppx_fields_conv
   ppx_sexp_conv)))
